config:
  ignore:
    paths:
      - /api/public/index.php
    commits:
      - 130af3f2fa6ea746e4358bf9f973510417457813
    file_extensions:
      - md
techstack:
  application:
    - laravel:9.52.15
    - php:8.0.2
    - quan12
    - quan12345
  database:
    - postgresql
    - linode
  devops:
    - kubernetes
    - fluxcd
    - docker
    - git
    - vscode
    - helm
  business_tools:
    - slack
    - figma
  utilities:
    - elasticsearch:8.11.1
    - metabase
